# Generated by Django 2.1.13 on 2019-10-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Colores de piel',
            },
        ),
        migrations.CreateModel(
            name='Contextura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('identificacion', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=250)),
                ('sintesis', models.TextField()),
                ('agresores_masculinos', models.IntegerField()),
                ('agresores_femeninos', models.IntegerField()),
                ('agresores_desconocidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='EstadoDenuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Estados Denuncias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('distrito_no', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoAfectado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cantidad', models.IntegerField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Denuncia')),
            ],
            options={
                'verbose_name_plural': 'Objetos Afectados',
            },
        ),
        migrations.CreateModel(
            name='ObjetoUtilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cantidad', models.IntegerField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Denuncia')),
            ],
            options={
                'verbose_name_plural': 'Objetos Utilizados',
            },
        ),
        migrations.CreateModel(
            name='PresuntoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('estatura_aprox', models.FloatField()),
                ('cabello', models.TextField()),
                ('tatuajes', models.TextField()),
                ('cicatrices', models.TextField()),
                ('color_piel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ColorPiel')),
                ('contextura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contextura')),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='app.Denuncia')),
            ],
            options={
                'verbose_name_plural': 'Presuntos Autores',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Testigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('identificacion', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testigos', to='app.Denuncia')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDelito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Tipos de delitos',
            },
        ),
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Tipos de lugares',
            },
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('identificacion', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victimas', to='app.Denuncia')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sexo')),
            ],
            options={
                'verbose_name_plural': 'Victimas',
            },
        ),
        migrations.AddField(
            model_name='presuntoautor',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sexo'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Municipio'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EstadoDenuncia'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Localidad'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_delito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TipoDelito'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='tipo_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TipoLugar'),
        ),
    ]
